---
- name: Compile war file
  hosts: web
  become: yes

  tasks:
  - name: install needs soft
    apt: name={{ item }} state=latest
    with_items:
      - default-jdk
      - maven 
      - git

  - name: clone git repository
    git:
      repo: 'https://github.com/benderinoz/war-hello.git'
      dest: /home/benderino/war-hello
  
  - name: compile war file
    shell: 'mvn package -f /home/benderino/war-hello'

- name: run war file on tomcat server
  hosts: db
  become: yes

  tasks:
  - name: install tomcat
    apt: name=tomcat9 state=present
  
  - name: ensure tomcat started
    service: name=tomcat9 state=started

  - name: copy war file on webapps
    synchronize:
      src: /home/benderino/war-hello/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/hello.war
    delegate_to: 192.168.1.112
